import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout.tsx
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className=" bg-[#181719] flex">
          <Header />
          <main className="flex-1 pt-6 overflow-y-auto">
          <div className="w-full h-full border border-gray-100/10 bg-[#111113] rounded-tl-xl p-6">
          {children}
          </div>
          </main>
        </div>
      </body>
    </html>
  );
}

